# Generated by Django 4.2 on 2024-05-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '__first__'),
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('grade', models.FloatField(default=0.0)),
                ('student_assignment_submission_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='students.studentsubmission')),
                ('teacher_assignment_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='teachers.testassignment')),
            ],
        ),
    ]
